[CIT-695] Remove tmp pkg
snyk/snyk-docker-pull pull request #120
Opened 2023-12-07 17:28 UTC by KatieArmstr

- [ ] Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
- [ ] Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)
- [x] Commit history is tidy [ℹ︎](https://github.com/snyk/general/wiki/Git)

### What this does

- remove tmp pkg and do the work natively
- make the tmp staging path dir configurable

### More information

- Jira ticket: https://snyksec.atlassian.net/browse/CIT-695

2023-12-07 17:37 UTC, KatieArmstr commented on src/docker-pull.ts
> +              path.join(stagingDirPath, `${name}-${randomUUID()}.tar`)
this was the previous implementation for name: 
```
  // prefix and postfix
  const name = [
    opts.prefix ? opts.prefix : 'tmp',
    '-',
    process.pid,
    '-',
    _randomChars(12),
    opts.postfix ? '-' + opts.postfix : ''
  ].join('');

  return path.join(tmpDir, opts.dir, name);
```
https://github.com/raszi/node-tmp/blob/aab7312cd615c75765efaa09470eedc3aa5b727d/lib/tmp.js#L483-L492

I replaced `process.pid, '-', _randomChars(12),` with `randomUUID()`

2023-12-07 17:59 UTC, jonnyowenpowell requested changes
I think this implementation will fail if `imageSaveDir` is set and `stagingDirPath` is not, because it attempts to create a link in the `stagingDirPath` regardless, which defaults to  `os.tmpdir()` which never gets created if `imageSaveDir` is set.

2023-12-07 17:59 UTC, jonnyowenpowell commented on src/docker-pull.ts
> +      const name = fs.mkdtempSync(`${stagingDirPath}${path.sep}`);
nit: `${path.sep}` is superfluous since this is only used in the context of `path.join` above.

2023-12-07 17:59 UTC, jonnyowenpowell commented on src/docker-pull.ts
> +              path.join(stagingDirPath, `${name}-${randomUUID()}.tar`)
This appears to now ignore `imageSavePath`, with the replacement of `stagingDir.name` by `stagingDirPath`. Is that intentional?

2023-12-07 18:24 UTC, KatieArmstr commented on src/docker-pull.ts
> +              path.join(stagingDirPath, `${name}-${randomUUID()}.tar`)
so in the original it gets the tmp directory like this:
```
function _getTmpDir(options) {
  return path.resolve(options && options.tmpdir || os.tmpdir());
}
```
but we did not set `options.tmpdir` so defaulted to `os.tmpdir()`.

2023-12-07 18:27 UTC, KatieArmstr commented on src/docker-pull.ts
> +              path.join(stagingDirPath, `${name}-${randomUUID()}.tar`)
if we wanted to change the default tmp directory via `stagingDirPath` we will need to do it here too

2023-12-07 18:44 UTC, KatieArmstr commented on src/docker-pull.ts
> +              path.join(stagingDirPath, `${name}-${randomUUID()}.tar`)
I don't think `imageSavePath` is involved at all here?
before: tempdir-name-randomstuff.tar
after tempdir-randomuuid.tar

where in the original `tempdir` was `os.tmpdir()`
and now `tempdir` is either `opt.stagingDirPath ` or `os.tmpdir()`

or am I missing something? 🤔

2023-12-08 10:27 UTC, jonnyowenpowell commented on src/docker-pull.ts
> +              path.join(stagingDirPath, `${name}-${randomUUID()}.tar`)
The tests actually cover this exact case (kind of by accident), so if you get them to pass, I'm happy. Based on that, I'll approve. If you have any trouble getting the tests, ping me; I'd be happy to help! 👍

2023-12-08 10:27 UTC, jonnyowenpowell approved these changes
LGTM 👍

2023-12-18 16:53 UTC, merged